AWSTemplateFormatVersion: "2010-09-09"
Description: Secrets Manager secret for DB credentials and Gemini config as one JSON secret

Parameters:
  RDSEndpoint:
    Type: String
    Description: RDS instance endpoint (imported or passed)
  S3BUCKET:
    Type: String
    Description: S3 Bucket Name (imported or passed)
  GEMINI_API_KEY:
    Type: String
    Description: GEMINI_API_KEY (imported or passed)

Resources:
  AppSecrets:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: app/secrets
      Description: "DB credentials and Gemini config"
      SecretString: !Sub |
        {
          "DB_USER": "admin",
          "DB_PASS": "password123",
          "DB_NAME": "app",
          "DB_HOST": "${RDSEndpoint}",
          "GEMINI_API_KEY": "${GEMINI_API_KEY}",
          "S3_BUCKET": "${S3Bucket}"
        }
      Tags:
        - Key: Application
          Value: MyApp

Outputs:
  SecretArn:
    Description: ARN of the created secret
    Value: !Ref AppSecrets
    Export:
      Name: AppSecretsArn
